name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.2
        with:
          owner: thatrobotdev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head: main
          base: main
